# Generated by Django 4.2 on 2023-04-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
