# Generated by Django 4.2 on 2023-04-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_interest_useraccount_user_interest_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user_id',
        ),
    ]
