# Generated by Django 4.2 on 2023-04-07 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraccount_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.interest'),
        ),
    ]
